# Generated by Django 3.0.7 on 2020-06-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NISIInvoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='first_name',
            field=models.CharField(max_length=256, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='last_name',
            field=models.CharField(max_length=256, verbose_name='Last Name'),
        ),
    ]
